spring:
  application:
    name: my-blog
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled:true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      image:
        options:
          model: gpt-image-1-mini