spring:
  application:
    name: my-blog
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      image:
        options:
          model: gpt-image-1-mini
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT-ID}
            client-secret: ${CLIENT-SECRET}
            scope:
              - email
              - profile
jwt:
  issuer: wc-blog-app
  secret_key: ${JWT_SECRET_KEY}
aws:
  s3:
    bucket: wcblog-bucket
    region: ap-northeast-2